# Generated by Django 6.0.1 on 2026-02-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='About Me', max_length=100)),
                ('body', models.TextField(help_text='Write in paragraphs. Line breaks will be preserved.')),
            ],
        ),
    ]
