# Generated by Django 6.0.1 on 2026-02-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_test', '0002_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=150)),
                ('year', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('start_date', models.CharField(max_length=20)),
                ('end_date', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
            ],
        ),
    ]
