# Generated by Django 6.0.1 on 2026-02-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_test', '0003_education_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(blank=True, choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('database', 'Database'), ('tools', 'Tools')], max_length=20),
        ),
        migrations.AddField(
            model_name='skill',
            name='level',
            field=models.IntegerField(blank=True, help_text='Skill level from 1 to 100', null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
