# Generated by Django 6.0.1 on 2026-02-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_test', '0005_alter_skill_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(blank=True, choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('database', 'Database'), ('tools', 'Tools'), ('languages', 'Languages'), ('frameworks', 'Frameworks'), ('concepts', 'Concepts')], max_length=20),
        ),
    ]
